name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Copy built files to NGINX directory
      run: sudo cp -r /home/ubuntu/realstate/realstate/react_ui_realstate/react_ui_realstate/dist/* /var/www/realstate/dist

    - name: Restart or Start PM2 process
      run: |
        if pm2 list | grep -q cicdreact; then
          pm2 restart cicdreact
        else
          pm2 start "npm" --name cicdreact -- run start -- --host
        fi
